function bw = segment(img)
%img = imread(fname);
img = rgb2gray(img);
img = imrotate(img,-12);
[imx,imy] = gaussgradient(img,0.1);
se = strel('line',15,90);
erode = imerode(imx,se);
ind = find(erode > 25);
erode(ind) = 255;
dilate  = imdilate(erode,se);
%figure,imshow(erode);
h = fspecial('gaussian');
smooth = imfilter(dilate,h);    
se = strel('disk',1);
%erodesm = imerode(smooth,se);
erodsm = imopen(smooth,se);
ind = find(erodsm > 25);
erodsm(ind) = 255;
diler = imdilate(erodsm,se);
%diler = imdilate(diler,se);
[n,m] = size(diler);
bw =  logical(zeros(n,m));
ind = find(diler == 255);
bw(ind) = 1;
%bw = bwmorph(bw,'skel');
%figure,imshow(bw,[]);
kernel = uint8(zeros(15,15));
kernel(4:12,7) = 1;
kernel(4:12,8) = -1;
kernel(4:12,9) = 1;
diler(:,:) = 0;
diler(ind) = 255;
co = conv2(diler,kernel);
[n,m] = size(diler);
%imwrite(co,'segmented.jpg');
bw = co;
%figure,imshow(imx);
%figure,imshow(imy);
end
